[project]
name = "yorimichi"
version = "0.1.0"
description = ""
authors = [
    {name = "victoriaghoos",email = "ghoosvictoria@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "osmnx (>=2.1.0,<3.0.0)",
    "networkx (>=3.6.1,<4.0.0)",
    "matplotlib (>=3.11.0,<4.0.0)",
    "scikit-learn (>=1.9.0,<2.0.0)",
    "scipy (>=1.18.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
