[project]
name = "yorimichi"
version = "0.1.0"
description = ""
authors = [
    {name = "victoriaghoos",email = "ghoosvictoria@gmail.com"}
]
readme = "../README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "osmnx (>=2.1.0,<3.0.0)",
    "networkx (>=3.6.1,<4.0.0)",
    "matplotlib (>=3.11.0,<4.0.0)",
    "scikit-learn (>=1.9.0,<2.0.0)",
    "scipy (>=1.18.0,<2.0.0)",
    "fastapi (>=0.139.0,<0.140.0)",
    "uvicorn (>=0.50.2,<0.51.0)",
    "sqlalchemy (>=2.0.51,<3.0.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "geoalchemy2 (>=0.20.0,<0.21.0)",
    "shapely (>=2.1.2,<3.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)"
]

[tool.poetry]
packages = [{include = "yorimichi", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "httpx2 (>=2.5.0,<3.0.0)",
    "osmium (>=4.3.1,<5.0.0)",
]

[tool.pytest.ini_options]
markers = [
    "integration: marks tests as integration tests (real network calls, slower)",
]